// nextjs/pages/get.tsx
import React, { useEffect, useState } from "react";

const Get = () => {
  const [data, setData] = useState<any[]>([]);

  useEffect(() => {
    const getData = () => {
      fetch("https://jsonplaceholder.typicode.com/posts")
        .then((response) => response.json())
        .then((json) => setData(json));
    };
    getData();
  }, []);

  return (
    <div>
      <h1>Get</h1>
      <div className="flex flex-wrap gap-2 justify-center">
        {data.map((el) => (
          <div
            className="border-2 border-black w-40 p-2"
            key={`${el.userId} - ${el.id}`}
          >
            <h1>{`UserId: ${el.userId} - ID: ${el.id}`}</h1>
            <h1>{el.title}</h1>
            <p>{el.body}</p>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Get;

// svelte/src/routes/get/+page.svelte
<script>

const getPosts = async()=>{
    const res = await fetch("https://jsonplaceholder.typicode.com/posts")
    const data = await res.json()
    return data
}
</script>

{#await getPosts()}
    <p>Loading...</p>
{:then data} 
<div class="container">
{#each data as {title, body}}
<div class="card">
    <h4 >{title}</h4>
    <p>{body}</p>
</div>
{/each}

</div>
{/await}

<style>
.container{
display: flex;
flex-wrap: wrap;
justify-content: space-between;
gap:16px;
padding: 16px;
}
.card{
border: 2px solid black;
width: 200px;
}

</style>
